name: Build and Deploy
on: [push]
jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build index
        run: python generate-index.py
      
      - name: Build base site
        uses: Tyler887/jekyllbuild@main
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: ghpages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
